name: Run Python Script with Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g
        ports:
          - 4444:4444

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Python script
      run: |
        docker run -v $(pwd):/mnt --network=host selenium/standalone-chrome:latest bash -c "pip install -r /mnt/requirements.txt && python3 /mnt/booster.py"
    
